### ISSUE TITLE
could not find the gold parse

### ISSUE THREAD

**Issue by kaeflint** [nitishgupta/conll-2012#2]
Tried running the scripts but had the error:
`could not find the gold parse [/shared/corpora/corporaWeb/multi-mode/multi/ontonotes-release-5.0/data/files/data/arabic/annotations/nw/ann/01/ann_0103.parse] in the ontonotes distribution ... exiting ...`

**Comment by nitishgupta** [comment]
You need to provide the ontonotes data yourself. In setup_training.sh change the ```ontonotes_path``` path to your own path.

**Comment by kusumlata123** [comment]
could not find the gold parse [/home/dr/Downloads/conll-2012-scripts.v3/conll-2012/v3/conll-2012/v4/data/train/data/arabic/annotations/nw/ann/03/ann_0343.parse] in the ontonotes distribution ... exiting ...
