### ISSUE TITLE
The errors with the code to process dataset

### ISSUE THREAD

**Issue by ghost** [nitishgupta/conll-2012#3]
Hi
I really appreciate your help, I have a deadline and would greatly be thankful to assist me process this dataset. thanks

SyntaxError: invalid syntax
Exit code: 1
conll-2012/v3/scripts/skeleton2conll.sh: line 93: break: only meaningful in a `for', `while', or `until' loop
-> python conll-2012/v?/scripts/skeleton2conll.py  /resource/database/ontonotes_rel_5/data/files/data/chinese/annotations/wb/e2c/00/e2c_0009.parse conll-2012/v9/data/test/data/chinese/annotations/wb/e2c/00/e2c_0009.v9_auto_skel conll-2012/v9/data/test/data/chinese/annotations/wb/e2c/00/e2c_0009.v9_auto_conll  --text
  File "conll-2012/v3/scripts/skeleton2conll.py", line 392
    except InvalidSexprException, e:
                                ^
SyntaxError: invalid syntax
Exit code: 1
conll-2012/v3/scripts/skeleton2conll.sh: line 93: break: only meaningful in a `for', `while', or `until' loop
cat: 'conll-2012/v4/data/development/data/english/annotations/*/*/*/*.v4_auto_conll': No such file or directory
cat: 'conll-2012/v4/data/train/data/english/annotations/*/*/*/*.v4_auto_conll': No such file or directory
cat: 'conll-2012/v4/data/test/data/english/annotations/*/*/*/*.v4_gold_conll': No such file or directory
Minimizing dev.english.v4_auto_conll
Wrote 0 documents to dev.english.jsonlines
Minimizing train.english.v4_auto_conll
Wrote 0 documents to train.english.jsonlines
Minimizing test.english.v4_gold_conll
Wrote 0 documents to test.english.jsonlines
mv: cannot create directory '/conll-2012': Permission denied
mv: cannot create regular file '/train.english.jsonlines': Permission denied
mv: cannot create regular file '/dev.english.jsonlines': Permission denied
mv: cannot create regular file '/test.english.jsonlines': Permission denied

**Comment by kusumlata123** [comment]
./skeleton2conll.sh -D /home/dr/Downloads/conll-2012/ /home/dr/Downloads/conll-2012/
find: ‘/home/dr/Downloads/conll-2012/v?/data/train/data/arabic/’: No such file or directory
find: ‘/home/dr/Downloads/conll-2012/v?/data/development/data/arabic/’: No such file or directory
----------------------------------------------------------------------------------------------------

could not find the gold parse [/home/dr/Downloads/conll-2012/arabic/annotations/nw/ann/03/ann_0399.parse] in the ontonotes distribution ... exiting ...

----------------------------------------------------------------------------------------------------

**Comment by kusumlata123** [comment]
./skeleton2conll.sh -D /home/dr/Downloads/conll-2012/ /home/dr/Downloads/conll-2012/
find: ‘/home/dr/Downloads/conll-2012/v?/data/train/data/arabic/’: No such file or directory
find: ‘/home/dr/Downloads/conll-2012/v?/data/development/data/arabic/’: No such file or directory
----------------------------------------------------------------------------------------------------

could not find the gold parse [/home/dr/Downloads/conll-2012/arabic/annotations/nw/ann/03/ann_0399.parse] in the ontonotes distribution ... exiting ...

----------------------------------------------------------------------------------------------------
 did you get solution for it.

**Comment by nitishgupta** [comment]
Sorry, I am not maintaining this project at all, neither was it meant for public use when I wrote it. 
As you can see from the README, parts of this code are from https://github.com/kentonl/e2e-coref. Maybe you'll find some help there.
